version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0

parameters:
  run_workflow_check_and_test:
    type: boolean
    default: true

commands:
  checkout-code:
    steps:
      - add_ssh_keys:
          fingerprints:
            - '91:82:dc:42:95:4f:4a:3b:db:32:5c:bc:c7:08:c8:6e'
      - checkout

  install-deps:
    steps:
      - ruby/install-deps
      - run: yarn build

  database-setup:
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database Setup
          command: bundle exec rake db:create db:schema:load

jobs:
  check:
    working_directory: ~/project
    docker:
      - image: cimg/ruby:2.7.6
    environment:
      RAILS_ENV: test
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
    resource_class: small
    steps:
      - checkout-code
      - ruby/install-deps

  test:
    working_directory: ~/project
    docker:
      - image: cimg/ruby:2.7.6
        environment:
          PGHOST: 127.0.0.1
          PGUSER: charityapi-circleci
          PGPASSWORD: password
      - image: cimg/postgres:11.14
        environment:
          POSTGRES_USER: charityapi-circleci
          POSTGRES_DB: charity-api_test
          POSTGRES_PASSWORD: password
    environment:
      RAILS_ENV: test
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
    resource_class: small
    steps:
      - checkout-code
      - install-deps
      - database-setup
      - ruby/rspec-test

workflows:
  check_and_test:
    when: << pipeline.parameters.run_workflow_check_and_test >>
    jobs:
      - check
      - test